export const Metadata: any = [
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreicu25bhpss2lg3jmt2bdqntwrjutjpnvpzgkemawhoqd6wpaouii4',
    name: 'Doners Doughnuts #1000001',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreih4c3waof2fv4prnaqtv2zfyyalttv5dqy3iicc35uezid3y4fvui',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'e3bbe56d7d5232fd4d9c2db60c815d7fb4fbec23',
      tokenId: 1000001,
      date: 1648663204172,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Red',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Mint',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Sprinkle',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Glasses',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreidkjtokmb5ts7fdknpuaf7qb5rmqzynn3xw3rlkt3t2znvmxxqhci',
    name: 'Doners Doughnuts #1000002',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreihty5qqnr2iombhvjz4i47ptzmgl53vsfz25vfuudv4lzjgxej75m',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'cb6b49e27e3be447f13ba17937c71b1edcb03c1f',
      tokenId: 1000002,
      date: 1648663204283,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Green',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Mint',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Candycorn',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Smirk',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Rapper',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreieyqnjczphghi6izzhkmjj4dqhxdhvdj7fjp3h5a75fgo5pkpjtgu',
    name: 'Doners Doughnuts #1000003',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreid3z5bf6r2tzgkyvueulmvaibiysayc3cc435ln3mnjhcsb4dcyza',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '5318fbea8537d4e7a039af0c92972e9214013abb',
      tokenId: 1000003,
      date: 1648663204393,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Purple',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Berry',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Heart',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Sleep',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreiewj3yyellig4n2rcaq3zfzxshc6f37ngt4t3gz2vcgcino5ufddq',
    name: 'Doners Doughnuts #1000004',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreibucgoahjadahpil7k3tvp6mexnhaj64mwqxbfxczk7b5vvpqwoe4',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'a3b51eac7698a0b7ff0df4cabb596cf9b8f845aa',
      tokenId: 1000004,
      date: 1648663204507,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Green',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Lemon',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Check',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Chill',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreif2mbj2zldug7atx2uz4vtihsvnpvek55osyck3iumvw3d4cd6gwq',
    name: 'Doners Doughnuts #1000005',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreig7cd2nswjivii37iwfaox75qwrvrseeoqjiihoidsczw2ktjrdtu',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'a60df3e5aa8c696a468e20d49a6d7bd10bc1c25e',
      tokenId: 1000005,
      date: 1648663204617,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Red',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Mint',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Heart',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Fox',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreia6fd3tgbgcwj566c4nddbi7pkfa3dnmqfnj3sjizmcuemyhvoxge',
    name: 'Doners Doughnuts #1000006',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreigcleh3tmestfwcnswop7edoyt6rjyuzuo26o5o7asgmkxoyep6su',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '161477ddbd86a8842863a9833d5a0de9721a291a',
      tokenId: 1000006,
      date: 1648663204729,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Orange',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Lemon',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Glaze',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Sweet',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreiehbr7elhwfi2yfoex2bru5usk3kvrsp3ibyd2wdad64hdbdzy2ay',
    name: 'Doners Doughnuts #1000007',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreihooro5cbzsa4as3r22onwvb4ygprxkpzx7fnmc5jlhc53ndx7s3m',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'f05268f24e97f455bb2bc347403e468b52dee520',
      tokenId: 1000007,
      date: 1648663204837,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Orange',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Blush',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Neon',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Blush',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreiatmemvxxl2blkbfxx4n6j3k3c5nomtvidwrr76mstg4s5a7ciak4',
    name: 'Doners Doughnuts #1000008',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreibiffsprec3oc2u4y7jlm5ysbgho25i3om22v2miwzxowga7tdcqe',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'e398251b9c7d81cf5650ed1c395f464a94250351',
      tokenId: 1000008,
      date: 1648663204946,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Red',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Mint',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Floral',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Sick',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreie2c76tnjo24gfevgj3bhzhviuxt3s3v2q7hygat2htv4cnfgeuam',
    name: 'Doners Doughnuts #1000009',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreierhqzxkl5tya74s3ibl5yoi35hgn5zokpszb6q4gm6bblin5wxha',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '13ee66aa8e8bcd911e45e5c554644ead89c7697e',
      tokenId: 1000009,
      date: 1648663205056,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Blue',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Orange',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Candycorn',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Smile',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreifougtzhj6h2fzaoqx4gfdruxilwxfhq6m5xmaykvq4g73wt54say',
    name: 'Doners Doughnuts #1000010',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreifnwr5nkgheedxziyt6uf47hdrchjdyupgzblbslezuloiqp6zqci',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'c4d2805e5f117b4efbd44a86355e65216e306ca8',
      tokenId: 1000010,
      date: 1648663205160,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Blue',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Orange',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Melt',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Sleep',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreigf6dc4lkfyfoxkn5rezlugsrlkwpurphtvxe3ngdkbsozn5uuyai',
    name: 'Doners Doughnuts #1000011',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreibc3cw77tuqnfkznmc66hposjg6e6747ydfyt6e4ib65vtigjg36i',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '99d762782daf8efcf117691d37298079ee4e3878',
      tokenId: 1000011,
      date: 1648663205265,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Red',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Frost',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Melt',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Chill',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreicdezykjqzm4xa3ysknn2lyy73rfzvo7pq47fw32ahlx5mz5ybm7i',
    name: 'Doners Doughnuts #1000012',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreiapxc7iftsr34usbpddhnp5cqztdaqevjlgpy3j3csokzch3dl4mm',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '7b1750973556506e000ac65756c555131040e71f',
      tokenId: 1000012,
      date: 1648663205371,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Blue',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Orange',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Floral',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Smirk',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreidi3q3yvupex2jfd32e5poggi7p7ikbf24k43oxl3ft4ukcoobknq',
    name: 'Doners Doughnuts #1000013',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreihfrvwd2nfljgpul74hjbceyhlimkxwsz2wle36wba77we6ry5zhy',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '5ad38f90cfb5d2c63b7fb3403938b65a7f751e36',
      tokenId: 1000013,
      date: 1648663205480,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Blue',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Cherry',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Party',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Sweat',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreier6mutpddfmuibed7emlo575h4lq7fc52z56notysobiflztdgri',
    name: 'Doners Doughnuts #1000014',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreidseucuuqpqa7mn4ulvt44uj57tkzdyjogxybma5annhez2aeqxwa',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '62707b28f2a7a5220f26559e734a7cef31a4b67e',
      tokenId: 1000014,
      date: 1648663205586,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Orange',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Simpsons',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Neon',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Blush',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreiaa3pszy6dvjtyiuwwb2i2deg5by7uudp5lsf3n7bk4vou7mslxtm',
    name: 'Doners Doughnuts #1000015',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreid2nxolr37sonnng2saq2mvulizvazntrrhs6a3fyqftspdyunmx4',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'bf7e13cd7634fa1b23016c490c225aba708f1e86',
      tokenId: 1000015,
      date: 1648663205695,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Orange',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Berry',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Party',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Fox',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreibpempqbtxpinivsp7xl3j2v7bxsrdccyyx3g5g5u4afwepkoidsi',
    name: 'Doners Doughnuts #1000016',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreigfc2okgerxycbqebqliyyvjgzdi2wxlojek74euz4cbozap2ym3e',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'd02257c730177ea61d64892f014946377cd7f235',
      tokenId: 1000016,
      date: 1648663205800,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Blue',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Berry',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Floral',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Chill',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreifpyb5o4ocmz3ddscf6efl77rxfyvkem2hg2dlvif6j727nzwwcze',
    name: 'Doners Doughnuts #1000017',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreihz44wwxwh7tzn5nz3pus3m7zrinrbmtgafl2lj2k4vci66otvp5q',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: 'cb7a050ce49a2668501907c09d2aa331f45f84ba',
      tokenId: 1000017,
      date: 1648663205904,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Blue',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Bubblegum',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Neon',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Smile',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreidm56jkgx25zft2xt6az72m7hxr4vpb5fedstltb7cxo6wfjxdtae',
    name: 'Doners Doughnuts #1000018',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreibsmg2ctse2qdezejkotzrlpe6mguivzqcb376vxd7forshy7lnqm',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '418ea5d5145bd61d7c7627f5798a6c23e40f732e',
      tokenId: 1000018,
      date: 1648663206011,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Green',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Strawberry',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Floral',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Smirk',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreifadbswcufl4cagdk66ucbn4lmfj32okig5kpiqqjoorgyjocn3nm',
    name: 'Doners Doughnuts #1000019',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreiblkqnj3wnlfud2oea6gnewkmvofef7hq67xlzobnnmfykwopdxei',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '4803570bcd00ff23c61a0d958659daed064f221d',
      tokenId: 1000019,
      date: 1648663206120,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Purple',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Mint',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Check',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Sweat',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
  {
    response: 'OK',
    metadata_uri:
      'ipfs://bafkreieo567neuh4jg6fcl2kiomg7w4jhuxbeihy2opzxpq2b5a27b223y',
    name: 'Doners Doughnuts #1000020',
    description: "NFT collection for the 'Doners'",
    file_url:
      'https://ipfs.io/ipfs/bafkreiayn4axh6oo5my2pclsiycfxyobwdf4egp57nzxvp2lgwzb32ksnm',
    external_url: 'https://j6a404.p.ssafy.io',
    animation_url: null,
    custom_fields: {
      dna: '73c29459640705d5b0ed2a4ec75b8fad23f41661',
      tokenId: 1000020,
      date: 1648663206226,
      compiler: 'Doners NFT Engine',
      edition: 'corona',
    },
    attributes: [
      {
        trait_type: 'Background',
        value: 'Green',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Frosting',
        value: 'Lemon',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Decoration',
        value: 'Heart',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Expression',
        value: 'Glasses',
        max_value: null,
        display_type: null,
      },
      {
        trait_type: 'Edition',
        value: 'Corona',
        max_value: null,
        display_type: null,
      },
    ],
    error: null,
  },
];
